import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-services',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './services.html',
  styleUrl: './services.scss',
})
export class Services {
  services = [
    {
      id: 'dotnet',
      icon: 'code',
      color: '#512BD4',
      title: '.NET Full Stack Solutions',
      subtitle: 'Web & Desktop Applications',
      description:
        'We design and develop enterprise-grade applications using the Microsoft .NET ecosystem. From responsive web apps to powerful desktop solutions, our team delivers reliable, performant software tailored to your workflows.',
      features: [
        'ASP.NET Core Web APIs & MVC applications',
        'Blazor WebAssembly & Server-side apps',
        'WPF & WinForms desktop applications',
        '.NET MAUI cross-platform apps',
        'Entity Framework Core & SQL Server',
        'SignalR real-time communication',
        'Identity & authentication systems',
        'Background services & job processing',
      ],
      technologies: [
        'C#',
        '.NET 8',
        'ASP.NET Core',
        'Blazor',
        'WPF',
        'MAUI',
        'EF Core',
        'SQL Server',
        'Redis',
        'RabbitMQ',
      ],
    },
    {
      id: 'azure',
      icon: 'cloud',
      color: '#0078D4',
      title: 'Azure Cloud Solutions',
      subtitle: 'Infrastructure & DevOps',
      description:
        'We help businesses migrate to and optimize on Microsoft Azure. From infrastructure setup to full DevOps pipelines, we design cloud architectures that scale with your growth and keep costs under control.',
      features: [
        'Cloud architecture design & consulting',
        'Azure App Service & Container deployments',
        'Azure Kubernetes Service (AKS)',
        'Serverless with Azure Functions',
        'CI/CD pipelines with Azure DevOps',
        'Azure SQL, Cosmos DB & storage solutions',
        'Monitoring, logging & alerting',
        'Security & compliance configurations',
      ],
      technologies: [
        'Azure',
        'Docker',
        'Kubernetes',
        'Terraform',
        'Azure DevOps',
        'App Service',
        'Functions',
        'Cosmos DB',
        'Key Vault',
        'Application Insights',
      ],
    },
    {
      id: 'wordpress',
      icon: 'layout',
      color: '#21759B',
      title: 'WordPress Development',
      subtitle: 'Content & Commerce',
      description:
        'We build fast, secure, and beautiful WordPress websites. Whether you need a corporate site, blog, or WooCommerce store, we create custom solutions that are easy to manage and optimized for performance.',
      features: [
        'Custom theme development from scratch',
        'Custom plugin development',
        'WooCommerce store setup & customization',
        'Performance optimization & caching',
        'SEO-ready architecture',
        'Headless WordPress with REST API',
        'Migration from other platforms',
        'Ongoing maintenance & support',
      ],
      technologies: [
        'WordPress',
        'PHP',
        'WooCommerce',
        'Elementor',
        'ACF',
        'REST API',
        'MySQL',
        'Nginx',
        'Cloudflare',
        'Yoast',
      ],
    },
    {
      id: 'shopify',
      icon: 'store',
      color: '#7AB55C',
      title: 'Shopify Development',
      subtitle: 'E-Commerce Solutions',
      description:
        'We create conversion-optimized Shopify stores that look stunning and sell effectively. From custom themes to app integrations, we handle every aspect of your Shopify presence.',
      features: [
        'Custom Shopify theme development',
        'Shopify Plus customization',
        'Liquid template development',
        'Custom app & integration development',
        'Payment gateway setup',
        'Product catalog & inventory management',
        'Conversion rate optimization',
        'Shopify to headless commerce migration',
      ],
      technologies: [
        'Shopify',
        'Liquid',
        'Shopify CLI',
        'Hydrogen',
        'Remix',
        'Storefront API',
        'Stripe',
        'Klaviyo',
        'Google Analytics',
        'Meta Pixel',
      ],
    },
  ];
}
